### ISSUE TITLE
Migrate to SupaBase (Postgres) for base setup 

### ISSUE THREAD

**Issue by ryaneggz** [promptengineers-ai/llm-server#129]

**Comment by devgenix** [comment]
Hi, @ryaneggz 
Can you provide a little more explanation on this? I'd like to help out.

**Comment by ryaneggz** [comment]
@devgenix I appreciate that! I actually just finished that piece up tonight the oss deploy is now utilizing it @ https://promptengineers-ai.netlify.app

I'm about to create another issue though to migrate the vector db to supabase as well.

The intention was to put all of the base architecture on freemium serverless architecture. This is to make it as frictionless & cheap as possible to get it deployed for themselves.

Currently the API is on Cloud Run and will scale to 0 (reason for long start ul times). The database(was mysql) and redis instance (current vectordb option) was on a digitalocean VM of mine.

Now that this issue is closed the database now resides on Supabase(postgres) so that piece no longer depends on the database I had on the VM. 

The next step is to no longer depend on the Redis vectordb on the VM as well. 

My intention is to use EITHER the PGVector Vectorstore or the SupaBase one they also have documented.

SupaBase Vectorstore
https://python.langchain.com/v0.2/docs/integrations/vectorstores/supabase/

PGVector(Postgres) Vectorstore
https://python.langchain.com/v0.2/docs/integrations/vectorstores/pgvector/

The SupaBase version appears to have some cool features as relates to Supa (which tbh I think they also have an open-source version as well), but I think the current goal is to start with support for most common. While SupaBase is currently the provider of choice its built on top of Postgres. 

In the end we'll prolly support both so which ever we add first doesn't matter to me. 

The goal is to provide free self-hosted options of the API (Cloud Run), DB's(Supa), and Frontend(I use netlify but this doesn't matter really... tons of easy options).

@devgenix Really you're welcome to pick up any of the issues and take a stab at them to get familiar and feel free to hmu on the slack channel if you have any questions. Link should be in the README.

**Comment by devgenix** [comment]
> @devgenix I appreciate that! I actually just finished that piece up tonight the oss deploy is now utilizing it @ https://promptengineersai.netlify.app
> 
> I'm about to create another issue though to migrate the vector db to supabase as well.
> 
> The intention was to put all of the base architecture on freemium serverless architecture. This is to make it as frictionless & cheap as possible to get it deployed for themselves.
> 
> Currently the API is on Cloud Run and will scale to 0 (reason for long start ul times). The database(was mysql) and redis instance (current vectordb option) was on a digitalocean VM of mine.
> 
> Now that this issue is closed the database now resides on Supabase(postgres) so that piece no longer depends on the database I had on the VM.
> 
> The next step is to no longer depend on the Redis vectordb on the VM as well.
> 
> My intention is to use EITHER the PGVector Vectorstore or the SupaBase one they also have documented.
> 
> SupaBase Vectorstore https://python.langchain.com/v0.2/docs/integrations/vectorstores/supabase/
> 
> PGVector(Postgres) Vectorstore https://python.langchain.com/v0.2/docs/integrations/vectorstores/pgvector/
> 
> The SupaBase version appears to have some cool features as relates to Supa (which tbh I think they also have an open-source version as well), but I think the current goal is to start with support for most common. While SupaBase is currently the provider of choice its built on top of Postgres.
> 
> In the end we'll prolly support both so which ever we add first doesn't matter to me.
> 
> The goal is to provide free self-hosted options of the API (Cloud Run), DB's(Supa), and Frontend(I use netlify but this doesn't matter really... tons of easy options).
> 
> @devgenix Really you're welcome to pick up any of the issues and take a stab at them to get familiar and feel free to hmu on the slack channel if you have any questions. Link should be in the README.

@ryaneggz I understand and I really support the purpose to make the base architecture use freemium services. 
You could also look into using Upstash VectorDB and Redis as well.

I'll take a look at other issues and see how I can help.
