### ISSUE TITLE
FEATURE: Add newly released GPT 4 turbo and vision to model options

### ISSUE THREAD

**Issue by ryaneggz** [promptengineers-ai/llm-server#2]
https://openai.com/blog/gpt-4-api-general-availability

![image](https://github.com/promptengineers-ai/llm-server/assets/40816745/43745776-50ff-4fff-b9ef-5b93595b9478)

**Comment by ryanformio** [comment]
Done in updated version

**Comment by ryaneggz** [comment]
Done
